/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caveiramenu;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Bandeira
 */
public class CAVEIRANOMENU extends javax.swing.JFrame {

    /**
     * Creates new form CAVEIRANOMENU
     */
    public CAVEIRANOMENU() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Jornada = new javax.swing.JButton();
        btn_Regras = new javax.swing.JButton();
        btn_AJUSTES = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Jornada.setText("COMEÇAR A JORNADA");
        btn_Jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JornadaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Jornada);
        btn_Jornada.setBounds(0, 490, 160, 60);

        btn_Regras.setText("REGRAS");
        btn_Regras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Regras);
        btn_Regras.setBounds(170, 490, 170, 60);

        btn_AJUSTES.setText("AJUSTES");
        btn_AJUSTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AJUSTESActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AJUSTES);
        btn_AJUSTES.setBounds(350, 490, 180, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas Bandeira\\Downloads\\caveira(jogo)\\CAVESKULL.jpg")); // NOI18N
        jLabel1.setText("ILHA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-9, 0, 2040, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_JornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JornadaActionPerformed
        JOptionPane.showMessageDialog(this, "Olá jogador, nesse jogo você embarcará em uma aventura perigosa e possivelmente mortal, mas primeiro você deve fazer uma escolha. E essa escolha é o seu personagem inicial: \n Johnny ou Sthepen");

    }//GEN-LAST:event_btn_JornadaActionPerformed

    private void btn_RegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegrasActionPerformed
        JOptionPane.showMessageDialog(this, "\n Não Trapacear, \n pedir ajuda ao Google, \n jogo singlplayer, \n não se beneficiar de bugs para avançar no jogo, ");
    }//GEN-LAST:event_btn_RegrasActionPerformed

    private void btn_AJUSTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AJUSTESActionPerformed
     JOptionPane.showMessageDialog(this, "\n ATIVAR/DESTIVAR MUSICAS  \n ATIVAR/DESATIVAR SOM DO JOGO \n AJUSTAR VOLUME \n ATIVAR/DESATIVAR AUTOSAVE");
    }//GEN-LAST:event_btn_AJUSTESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAVEIRANOMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAVEIRANOMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAVEIRANOMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAVEIRANOMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAVEIRANOMENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AJUSTES;
    private javax.swing.JButton btn_Jornada;
    private javax.swing.JButton btn_Regras;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
